linters:
  disable-all: true
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gocritic

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

run:
  deadline: 5m
  tests: true

output:
  format: colored-line-number

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
